from LinkedList import LinkedList

ll = LinkedList()
ll.display()
ll.append(10)
ll.append(20)
ll.append(30)
ll.append(40)
ll.append(50)
ll.display()
ll.insert(1, 99)
ll.display()
ll.insert(0, 909)
ll.display()
ll.delete(1)
ll.display()